# Generated by Django 4.1 on 2022-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_status',
            name='status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Refeição', 'Refeição'), ('Pausa', 'Pausa'), ('Férias', 'Férias')], default='Online', help_text='status', max_length=15),
        ),
        migrations.AddField(
            model_name='dados_status',
            name='turno',
            field=models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default='C1', help_text='Turno Atual de trabalho', max_length=2),
        ),
    ]
